/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProductFinderChangeWheelColorRouteImport } from './routes/product-finder.change-wheel-color'
import { Route as ProductFinderCustomFinishRouteImport } from './routes/product-finder.custom-finish'
import { Route as ProductFinderOemRestoreRouteImport } from './routes/product-finder.oem-restore'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductFinderChangeWheelColorRoute =
  ProductFinderChangeWheelColorRouteImport.update({
    id: '/product-finder/change-wheel-color',
    path: '/product-finder/change-wheel-color',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductFinderCustomFinishRoute =
  ProductFinderCustomFinishRouteImport.update({
    id: '/product-finder/custom-finish',
    path: '/product-finder/custom-finish',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductFinderOemRestoreRoute = ProductFinderOemRestoreRouteImport.update({
  id: '/product-finder/oem-restore',
  path: '/product-finder/oem-restore',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/product-finder/change-wheel-color': typeof ProductFinderChangeWheelColorRoute
  '/product-finder/custom-finish': typeof ProductFinderCustomFinishRoute
  '/product-finder/oem-restore': typeof ProductFinderOemRestoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/product-finder/change-wheel-color': typeof ProductFinderChangeWheelColorRoute
  '/product-finder/custom-finish': typeof ProductFinderCustomFinishRoute
  '/product-finder/oem-restore': typeof ProductFinderOemRestoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/product-finder/change-wheel-color': typeof ProductFinderChangeWheelColorRoute
  '/product-finder/custom-finish': typeof ProductFinderCustomFinishRoute
  '/product-finder/oem-restore': typeof ProductFinderOemRestoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/product-finder/change-wheel-color'
    | '/product-finder/custom-finish'
    | '/product-finder/oem-restore'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/product-finder/change-wheel-color'
    | '/product-finder/custom-finish'
    | '/product-finder/oem-restore'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/product-finder/change-wheel-color'
    | '/product-finder/custom-finish'
    | '/product-finder/oem-restore'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProductFinderChangeWheelColorRoute: typeof ProductFinderChangeWheelColorRoute
  ProductFinderCustomFinishRoute: typeof ProductFinderCustomFinishRoute
  ProductFinderOemRestoreRoute: typeof ProductFinderOemRestoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-finder/change-wheel-color': {
      id: '/product-finder/change-wheel-color'
      path: '/product-finder/change-wheel-color'
      fullPath: '/product-finder/change-wheel-color'
      preLoaderRoute: typeof ProductFinderChangeWheelColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-finder/custom-finish': {
      id: '/product-finder/custom-finish'
      path: '/product-finder/custom-finish'
      fullPath: '/product-finder/custom-finish'
      preLoaderRoute: typeof ProductFinderCustomFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-finder/oem-restore': {
      id: '/product-finder/oem-restore'
      path: '/product-finder/oem-restore'
      fullPath: '/product-finder/oem-restore'
      preLoaderRoute: typeof ProductFinderOemRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProductFinderChangeWheelColorRoute: ProductFinderChangeWheelColorRoute,
  ProductFinderCustomFinishRoute: ProductFinderCustomFinishRoute,
  ProductFinderOemRestoreRoute: ProductFinderOemRestoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
